---
title: "Indice Pobreza AGEB"
author: "Gonzalo"
date: "7/9/2021"
output: html_document
---

# Script análisis bases de datos Indice de Pobreza Municipal

## Crear y establacer directorios de trabajo

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/")
```


```{r}

if (!dir.exists("analisis_ipAGEB")) {
  dir.create("analisis_ipAGEB")
}
setwd("~/analisis_ipAGEB")

```

### URL que contiene la descarga del archivo comprimido con las bases de datos:

```{r}
url_ipAGEB <- "https://www.coneval.org.mx/Informes/Pobreza/Datos_abiertos/Pobreza_urbana/Rangos%20de%20pobreza%20y%20pobreza%20extrema%20a%20nivel%20AGEB%2C%202015.csv"
```

### Variable con el nombre del archivo que interesa

```{r}

ipAGEB_file <- "Rangos de pobreza y pobreza extrema a nivel AGEB, 2015.csv"

```

### Verificación y descarga de bases de datos 

```{r}

if (!file.exists(ipAGEB_file)) {
  download.file(url_ipAGEB, ipAGEB_file, mode = "wb")
}

```

### Cargar CSVs de bases de datos en sesion de R.

```{r}

library(readr)
IndicePobrezaMunicipalAGEB <- read_csv("Rangos de pobreza y pobreza extrema a nivel AGEB, 2015.csv")

```

### Explorar base de datos

```{r}
head(IndicePobrezaMunicipalAGEB)
tail(IndicePobrezaMunicipalAGEB)
str(IndicePobrezaMunicipalAGEB)
summary(IndicePobrezaMunicipalAGEB)

IndicePobrezaMunicipalAGEB[!complete.cases(IndicePobrezaMunicipalAGEB),]
```

